### ISSUE TITLE
How do i run this and does this program work outside China

### ISSUE THREAD

**Issue by BonnY0** [howardchn/PhoneNumberLocator-JS#1]
pls help

**Comment by ginkgoch** [comment]
Not exactly work outside of China, but I can give the idea how I support it inside China.

1. http://ws.webxml.com.cn/WebServices/MobileCodeWS.asmx is the the web service to get city name by cellphone number. Due to the service only support to search inside China, thus this is point where you'd like to replace
1. https://groups.google.com/d/topic/google-maps-js-api-v3/Ly4EHKYMFSc once you find the city or location name, call Google GeoCoder API would return you the corresponding geolocation

**Comment by howardchn** [comment]
Not support outside China due to the [webservice](http://ws.webxml.com.cn/WebServices/MobileCodeWS.asmx) only support to find location name inside China. If you replace this part, the next step is also compatible to find geolocation by location name by Google Geocoder service.
